import Image from "next/image";
import { isSyntheticEvent, SYNTHETIC_DISCLOSURE, SYNTHETIC_PROOF_DISCLOSURE } from "@/lib/demo";
import Link from "next/link";
import type { PublicResult } from "./public-reveal";
import { AttributionChart, RankChart } from "./charts";
import CopyReportLink from "./CopyReportLink";
import { brandKey, byRoomRank, formatCorrelation, formatDate, formatMean, formatPValue, formatRank, rankedProducts } from "./format";

export default function ReportView({ result, fixture = false }: { result: PublicResult; fixture?: boolean }) {
  const { event, reveal } = result;
  const synthetic = fixture || isSyntheticEvent(event);
  const ranked = byRoomRank(reveal);
  const predicted = rankedProducts(reveal);
  const winner = ranked.find((item) => item.room && item.room.votes > 0 && item.room.rank === 1);
  const tasted = reveal.actual.filter((item) => item.votes > 0).length;
  const brands = [...new Set([...reveal.brandPredicted.map((row) => brandKey(row.brand)), ...reveal.brandActual.map((row) => brandKey(row.brand)), ...reveal.predicted.map((row) => brandKey(row.brand))])]
    .map((key) => ({
      key,
      name: reveal.brandActual.find((row) => brandKey(row.brand) === key)?.brand ?? reveal.brandPredicted.find((row) => brandKey(row.brand) === key)?.brand ?? reveal.predicted.find((row) => brandKey(row.brand) === key)?.brand ?? key,
      actual: reveal.brandActual.find((row) => brandKey(row.brand) === key),
      ai: reveal.brandPredicted.find((row) => brandKey(row.brand) === key),
      products: predicted.filter((row) => brandKey(row.brand) === key).sort((a, b) => (a.room?.votes && a.room.rank ? a.room.rank : Infinity) - (b.room?.votes && b.room.rank ? b.room.rank : Infinity)),
      comments: reveal.comments.filter((row) => brandKey(row.brand) === key),
    }))
    .sort((a, b) => (a.actual?.rank && a.products.some((row) => row.room?.votes) ? a.actual.rank : Infinity) - (b.actual?.rank && b.products.some((row) => row.room?.votes) ? b.actual.rank : Infinity) || (a.ai?.rank ?? Infinity) - (b.ai?.rank ?? Infinity));
  const deckHref = fixture ? `/fixtures/${event.slug}?view=reveal` : `/e/${event.slug}/reveal`;
  const exportHref = fixture ? `/api/fixtures/${event.slug}` : `/api/e/${event.slug}/report`;

  return (
    <main className="min-h-dvh bg-stone-50 font-sans text-slate-900">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-4 sm:px-8">
          <Link href={fixture ? "/fixtures" : "/"} className="flex items-center gap-3 rounded font-semibold tracking-tight focus-visible:outline-2 focus-visible:outline-emerald-700"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-950 font-mono text-lg text-emerald-300">S</span><span>Shelf Oracle <span className="hidden font-normal text-slate-500 sm:inline">/ Field report</span></span></Link>
          <div className="flex items-center gap-4 text-sm"><Link href={fixture ? "/fixtures" : `/e/${event.slug}`} className="rounded text-slate-600 hover:text-slate-950 focus-visible:outline-2 focus-visible:outline-emerald-700">{fixture ? "Fixtures" : "Event"}</Link><Link href={deckHref} className="rounded font-medium text-slate-900 hover:text-emerald-700 focus-visible:outline-2 focus-visible:outline-emerald-700">View reveal →</Link></div>
        </div>
      </header>

      <div className="mx-auto max-w-7xl px-4 pb-24 sm:px-8">
        {synthetic && <aside role="note" aria-label="Synthetic demo disclosure" className="mt-6 rounded-2xl border-2 border-amber-400 bg-amber-50 p-4 text-sm leading-relaxed text-amber-950 sm:p-6"><strong className="block font-semibold">SYNTHETIC / DEMO{fixture ? " · Local fixture" : " · Demo/test event"}</strong><p className="mt-1">{SYNTHETIC_DISCLOSURE}</p><p className="mt-2">{SYNTHETIC_PROOF_DISCLOSURE}</p></aside>}
        <section className="border-b border-slate-200 pb-10 pt-12 sm:pb-16 sm:pt-20">
          <div className="flex flex-wrap items-center gap-3 text-xs font-semibold uppercase tracking-[0.18em] text-slate-600"><span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-900">{fixture ? "Synthetic fixture" : synthetic ? "SYNTHETIC / DEMO result" : "Published result"}</span><span>Field report / {formatDate(reveal.generatedAt)}</span></div>
          <div className="mt-7 grid gap-8 lg:grid-cols-[1.4fr_0.6fr] lg:items-end">
            <div><p className="break-words text-sm font-medium text-emerald-800">{event.name}{event.location ? ` · ${event.location}` : ""}</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-[1.03] tracking-tight sm:text-7xl">{synthetic ? <>A simulated room. <span className="text-emerald-700">A demo result.</span></> : <>What the room <span className="text-emerald-700">really wanted.</span></>}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-slate-700 sm:text-lg">{synthetic ? "A demo prediction compared with simulated ratings and guesses. These sample results illustrate the workflow, not actual shopper preferences." : "An AI ranking locked before tasting, compared with real ratings and human guesses. This is the public record of one event, not a claim about every shopper."}</p></div>
            <div className="grid grid-cols-3 gap-2 rounded-2xl border border-slate-200 bg-white p-4 lg:grid-cols-1 lg:gap-3 lg:p-6">
              {[[reveal.voterCount, "voters"], [reveal.voteCount, "ratings"], [formatCorrelation(reveal.metrics.spearman), "AI ↔ room rank ρ"]].map(([value, label]) => <div key={label} className="min-w-0 lg:flex lg:items-end lg:justify-between lg:border-b lg:border-slate-100 lg:pb-2"><strong className="block break-words font-mono text-xl tabular-nums sm:text-3xl">{value}</strong><span className="block text-xs text-slate-600">{label}</span></div>)}
            </div>
          </div>
          <div className="mt-8 flex flex-wrap items-start gap-3"><a href={exportHref} download={`${event.slug}-public-report.json`} className="inline-flex min-h-11 items-center justify-center rounded-full bg-slate-950 px-5 text-sm font-semibold text-white hover:bg-slate-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700">Download public JSON ↓</a><CopyReportLink /></div>
          <nav aria-label="Report sections" className="mt-8 flex flex-wrap gap-x-5 gap-y-2 border-t border-slate-200 pt-5 text-xs font-medium text-slate-600 sm:text-sm">{[["result", "Result"], ["rankings", "Rankings"], ["brands", "Brands"], ["people", "People"], ["methods", "Methods & limits"]].map(([id, text]) => <a key={id} href={`#${id}`} className="rounded hover:text-emerald-700 focus-visible:outline-2 focus-visible:outline-emerald-700">{text} ↘</a>)}</nav>
        </section>

        <section id="result" className="scroll-mt-10 border-b border-slate-200 py-12 sm:py-16">
          <div className="mb-8 flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-widest text-emerald-800">01 / The result</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Prediction meets tasting.</h2></div><p className="max-w-sm text-sm text-slate-600">{synthetic ? "Purple: demo prediction rank. Cyan: simulated top-five guess consensus. Green: rank from simulated ratings." : "Purple: pre-tasting AI rank. Cyan: consensus of human top-five guesses. Green: actual tasting rank from submitted ratings."}</p></div>
          {winner ? <div className="mb-8 grid gap-3 rounded-3xl bg-slate-950 p-6 text-white sm:p-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="font-mono text-xs uppercase tracking-widest text-emerald-300">Room favourite / #1 rated product</p><h3 className="mt-4 break-words text-3xl font-semibold tracking-tight sm:text-5xl">{winner.brand} · {winner.name}</h3><p className="mt-4 text-sm text-slate-300">{winner.room!.votes} ratings · raw mean {formatMean(winner.room?.mean)}/5 · AI predicted {formatRank(winner.rank)}</p></div><span className="font-mono text-6xl tabular-nums text-emerald-300 sm:text-8xl">#1</span></div> : <p className="mb-8 rounded-2xl border border-slate-200 bg-white p-6 text-slate-600">No tasted product has a room rank.</p>}
          <RankChart reveal={reveal} light />
          <div className="mt-10 grid gap-3 sm:grid-cols-3">
            <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">Rank correlation · Spearman ρ</p><strong className="mt-3 block font-mono text-3xl tabular-nums text-violet-800 sm:text-4xl">{formatCorrelation(reveal.metrics.spearman)}</strong><p className="mt-2 text-xs text-slate-600">+1 identical order; −1 reversed order. Only mutually ranked products can contribute.</p></div>
            <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">Two-sided permutation test</p><strong className="mt-3 block font-mono text-3xl tabular-nums sm:text-4xl">{formatPValue(reveal.metrics.pValue)}</strong><p className="mt-2 text-xs text-slate-600">Chance of at least this rank correlation under random reorderings; not a population inference.</p></div>
            <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">Top-five overlap</p><strong className="mt-3 block font-mono text-3xl tabular-nums text-emerald-800 sm:text-4xl">{reveal.metrics.topKOverlap}</strong><p className="mt-2 text-xs text-slate-600">Shared products in AI top five and room&apos;s up-to-five tasted leaders.</p></div>
          </div>
        </section>

        <section id="rankings" className="scroll-mt-10 border-b border-slate-200 py-12 sm:py-16">
          <p className="font-mono text-xs uppercase tracking-widest text-emerald-800">02 / Every product</p>
          <h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">The full shelf, ranked.</h2>
          <p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-600">Room ranks use adjusted ratings; means below are raw averages on a 1–5 scale. Products without ratings are marked untasted and never assigned a room rank. Human rank is Borda consensus from submitted top-five guesses.</p>
          <div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white">
            <div className="hidden grid-cols-[minmax(0,1fr)_5rem_5rem_7rem_7rem_5rem] gap-3 bg-slate-100 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-600 md:grid"><span>Product</span><span>AI rank</span><span>Room</span><span>Raw mean / n</span><span>Adjusted / 5</span><span>Human</span></div>
            {ranked.length ? <ol>{ranked.map((item) => <li key={item.productId} className="grid gap-4 border-t border-slate-100 px-4 py-5 first:border-t-0 sm:px-5 md:grid-cols-[minmax(0,1fr)_5rem_5rem_7rem_7rem_5rem] md:items-center md:gap-3">
              <div className="flex min-w-0 items-center gap-3">{item.thumb ? <Image src={item.thumb} width={48} height={52} unoptimized alt={`Packaging for ${item.brand} ${item.name}`} className="h-13 w-12 shrink-0 rounded-md border border-slate-200 object-contain" /> : <span aria-hidden="true" className="flex h-13 w-12 shrink-0 items-center justify-center rounded-md bg-stone-100 font-mono text-lg text-slate-500">S</span>}<div className="min-w-0"><p className="break-words font-semibold">{item.brand}</p><p className="break-words text-sm text-slate-600">{item.name}</p></div></div>
              <div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-5 md:contents"><div><span className="block text-slate-500 md:hidden">AI</span><strong className="font-mono text-sm tabular-nums text-violet-800">{formatRank(item.rank)}</strong></div><div><span className="block text-slate-500 md:hidden">Room</span><strong className="font-mono text-sm tabular-nums text-emerald-800">{item.room?.votes && item.room.rank ? formatRank(item.room.rank) : "Untasted"}</strong></div><div><span className="block text-slate-500 md:hidden">Raw / n</span><span className="block font-mono text-sm tabular-nums">{item.room?.votes ? `${formatMean(item.room.mean)} / ${item.room.votes}` : "—"}</span></div><div><span className="block text-slate-500 md:hidden">Adjusted</span><span className="block font-mono text-sm tabular-nums">{item.room?.votes ? formatMean(item.room.adjustedMean) : "—"}</span></div><div><span className="block text-slate-500 md:hidden">Human</span><span className="block font-mono text-sm tabular-nums">{formatRank(item.human?.rank)}</span></div></div>
            </li>)}</ol> : <p className="p-6 text-slate-600">No products included in the public reveal.</p>}
          </div>
          <p className="mt-3 text-xs text-slate-600">“Raw mean / n” displays raw mean rating and rating count; adjusted mean is used for room ranking when available. A dash means no rank or rating was available; it does not mean zero.</p>
        </section>

        <section id="brands" className="scroll-mt-10 border-b border-slate-200 py-12 sm:py-16">
          <p className="font-mono text-xs uppercase tracking-widest text-emerald-800">03 / Brand pages</p>
          <h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">A card for every brand.</h2>
          <p className="mt-4 max-w-3xl text-sm leading-relaxed text-slate-600">Brand rank follows the brand&apos;s best-ranked tasted SKU; the mean shown is that SKU&apos;s raw average, not an average of all brand products.</p>
          {brands.length ? <div className="mt-8 grid gap-5 lg:grid-cols-2">{brands.map((brand) => <article key={brand.key} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
            <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="font-mono text-xs uppercase tracking-widest text-slate-500">Brand / tasting record</p><h3 className="mt-2 break-words text-2xl font-semibold tracking-tight sm:text-3xl">{brand.name}</h3></div><span className="rounded-full bg-emerald-50 px-3 py-1 font-mono text-sm text-emerald-900">{brand.actual?.rank && brand.products.some((item) => item.room?.votes) ? `Room #${brand.actual.rank}` : "Untasted"}</span></div>
            <div className="mt-6 grid grid-cols-3 gap-2 border-y border-slate-100 py-4 text-xs text-slate-600"><div><strong className="block font-mono text-lg tabular-nums text-violet-800 sm:text-xl">{formatRank(brand.ai?.rank)}</strong>AI brand rank</div><div><strong className="block font-mono text-lg tabular-nums text-slate-950 sm:text-xl">{brand.actual?.rank && brand.products.some((item) => item.room?.votes) ? formatMean(brand.actual.mean) : "—"}</strong>best SKU mean / 5</div><div><strong className="block font-mono text-lg tabular-nums text-slate-950 sm:text-xl">{brand.products.filter((item) => item.room?.votes).length} / {brand.products.length}</strong>SKUs rated / total</div></div>
            <ul className="mt-4 space-y-3">{brand.products.map((item) => <li key={item.productId} className="flex items-start justify-between gap-4 text-sm"><span className="min-w-0 break-words text-slate-700">{item.name}</span><span className="shrink-0 font-mono tabular-nums text-slate-600">{item.room?.votes && item.room.rank ? `${formatRank(item.room.rank)} · ${formatMean(item.room.mean)}/5 · n=${item.room.votes}` : "Untasted"}</span></li>)}</ul>
            {brand.comments.length > 0 && <figure className="mt-6 border-l-2 border-emerald-400 pl-4"><blockquote className="break-words text-sm leading-relaxed text-slate-700">“{brand.comments[0].text}”</blockquote><figcaption className="mt-2 text-xs text-slate-600">Submitted for {brand.comments[0].product} · {brand.comments[0].rating}/5</figcaption></figure>}
          </article>)}</div> : <p className="mt-8 text-slate-600">No brand rankings were included.</p>}
        </section>

        <section id="people" className="scroll-mt-10 border-b border-slate-200 py-12 sm:py-16">
          <p className="font-mono text-xs uppercase tracking-widest text-emerald-800">04 / Beyond the algorithm</p>
          <h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">{synthetic ? "The simulated participants." : "The people in the room."}</h2>
          <div className="mt-8 grid gap-5 lg:grid-cols-2">
            <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h3 className="text-xl font-semibold">Human predictions</h3><p className="mt-2 text-sm text-slate-600">{reveal.guesserCount} guesses submitted. Human consensus vs room Spearman ρ: <strong className="font-mono tabular-nums text-emerald-800">{formatCorrelation(reveal.metrics.humanSpearman)}</strong>. {tasted && reveal.metrics.humansTotal ? `AI beat ${reveal.metrics.aiBeatsHumans} of ${reveal.metrics.humansTotal} scored individual predictors.` : "No individual comparison was available."}</p>{reveal.consensus.length ? <ol className="mt-5 space-y-3">{reveal.consensus.slice(0, 5).map((item) => <li key={item.productId} className="flex justify-between gap-2 border-t border-slate-100 pt-3 text-sm"><span className="min-w-0 break-words">#{item.rank} {predicted.find((p) => p.productId === item.productId)?.name ?? "Product not in AI lineup"}</span><span className="shrink-0 font-mono tabular-nums text-slate-600">{item.points} pts</span></li>)}</ol> : <p className="mt-4 text-sm text-slate-600">No consensus ranking available.</p>}<p className="mt-4 text-xs text-slate-600">Top-five guesses use Borda points: 5 for first place down to 1 for fifth.</p></div>
            <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h3 className="text-xl font-semibold">Predictor leaderboard</h3>{tasted > 0 && reveal.leaderboard.length ? <ol className="mt-5 space-y-3">{reveal.leaderboard.map((entry, index) => <li key={`${entry.name}-${index}`} className="flex items-center justify-between gap-2 border-t border-slate-100 pt-3 text-sm"><span className="min-w-0 break-words">{index + 1}. {entry.name}</span><span className="shrink-0 font-mono tabular-nums text-slate-600">{entry.score}/100</span></li>)}</ol> : <p className="mt-4 text-sm text-slate-600">No predictor leaderboard available.</p>}<p className="mt-5 text-xs text-slate-600">{synthetic ? "Demo scores compare simulated guesses and ratings. Participant names are simulated; they are not real customer identities." : "Scores compare submitted top-five guesses to the event's tasted leaders. Human names are submitted display names; Shelf Oracle AI is the model entry."}</p></div>
          </div>
          <div className="mt-10"><h3 className="text-2xl font-semibold">What tracked with ratings</h3><p className="mt-2 mb-5 text-sm text-slate-600">Observed r correlates each AI principle score with ratings across tasted products; weight is the AI rubric input. It is not a causal explanation.</p><AttributionChart reveal={reveal} light /><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-600">{reveal.attribution.map((item, i) => <span key={`${item.principle}-${i}`} className="break-words">{item.principle}: weight {item.weight}</span>)}</div></div>
        </section>

        <section className="border-b border-slate-200 py-12 sm:py-16"><p className="font-mono text-xs uppercase tracking-widest text-emerald-800">05 / Learnings from the room</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">The misses, and the voices.</h2>
          <h3 className="mt-10 text-xl font-semibold">Highlighted ranking misses</h3><p className="mt-2 text-sm text-slate-600">Post-vote notes are interpretations (model-generated when available), not measured causes.</p>
          {reveal.misses.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{reveal.misses.map((item, i) => <article key={`${item.productId}-${i}`} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h4 className="break-words font-semibold">{item.brand} · {item.name}</h4><p className="mt-2 font-mono text-sm tabular-nums text-violet-800">AI #{item.predictedRank} → room #{item.actualRank}</p><p className="mt-4 break-words text-sm leading-relaxed text-slate-700">{item.note}</p></article>)}</div> : <p className="mt-4 text-sm text-slate-600">No highlighted misses in this result.</p>}
          <h3 className="mt-12 text-xl font-semibold">{synthetic ? "Simulated written comments" : "Real written comments"}</h3><p className="mt-2 text-sm text-slate-600">{synthetic ? "Demo comments, not authentic customer testimonials or evidence of retail demand." : "Direct excerpts from submitted votes. No AI-written testimonials."}</p>
          {reveal.comments.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{reveal.comments.map((entry, i) => <figure key={`${entry.product}-${i}`} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><blockquote className="break-words text-base leading-relaxed text-slate-800">“{entry.text}”</blockquote><figcaption className="mt-4 break-words text-xs text-slate-600">{entry.brand} · {entry.product} · {entry.rating}/5 submitted rating</figcaption></figure>)}</div> : <p className="mt-4 text-sm text-slate-600">No written tasting comments were included.</p>}
        </section>

        <section id="methods" className="scroll-mt-10 py-12 sm:py-16"><p className="font-mono text-xs uppercase tracking-widest text-emerald-800">06 / Method & limits</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">How to read this report.</h2>
          <div className="mt-8 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-semibold">The lock</h3><p className="mt-3 text-sm leading-relaxed text-slate-700">{synthetic ? SYNTHETIC_PROOF_DISCLOSURE : "The server recorded a SHA-256 fingerprint of the locked prediction before voting."} Fingerprint: <span className="break-all font-mono">{reveal.lockHash || "Unavailable"}</span>. {synthetic ? "Demo payload hash match" : "Reveal-time hash match"}: <strong>{reveal.verified && reveal.lockHash ? "Confirmed" : "Not confirmed"}</strong>. {synthetic ? "The public JSON can be used to inspect the demo payload. Hash consistency does not establish when a prediction was made or prove real market performance." : "The public JSON download includes the canonical locked payload, so you can independently compute its SHA-256 hash and compare it with the fingerprint displayed before voting."}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-semibold">The ratings</h3><p className="mt-3 text-sm leading-relaxed text-slate-700">{reveal.voterCount} {synthetic ? "simulated voters contributed" : "distinct voters submitted"} {reveal.voteCount} {synthetic ? "simulated ratings" : "ratings"} for {tasted} {synthetic ? "demo products" : "tasted products"}. Means are raw scores on a 1–5 scale; room rank uses a Bayesian-adjusted mean (three-rating prior toward the event mean). Untasted products have no room rank. Brand rank is the best-ranked tasted SKU.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-semibold">The comparisons</h3><p className="mt-3 text-sm leading-relaxed text-slate-700">Spearman ρ measures agreement between two rank lists. The two-sided p-value uses permutation of rank order. Null or unavailable metrics mean a comparison could not be calculated; a zero should not be read as missing. Human guesses are ordered top-five lists aggregated using Borda points. Principle correlations describe association, not why shoppers rated a product.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-semibold">The limits</h3><p className="mt-3 text-sm leading-relaxed text-slate-700">One self-selected tasting room is not a representative shopper sample. Products may have different numbers of ratings. Neither correlations nor a small p-value establish causation or out-of-sample predictive performance. Miss notes are post-vote interpretations; comments are participant submissions.</p></div></div>
          <div className="mt-10 flex flex-wrap items-center justify-between gap-4 border-t border-slate-200 pt-8 text-sm text-slate-600"><span>Published {formatDate(reveal.generatedAt)} · Shelf Oracle</span><a href={exportHref} className="font-medium text-slate-900 underline underline-offset-4 hover:text-emerald-700 focus-visible:outline-2 focus-visible:outline-emerald-700">Download public data (JSON) ↗</a></div>
        </section>
      </div>
    </main>
  );
}
